# Generated by Django 5.2.1 on 2025-05-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecanteResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.FloatField()),
                ('x1', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('max_iteraciones', models.IntegerField()),
                ('raiz', models.FloatField()),
                ('iteraciones_usadas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
