# Generated by Django 5.2.1 on 2025-05-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secante_app', '0002_rename_iteraciones_usadas_secanteresultado_max_iter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=255)),
                ('valor_inicial', models.FloatField()),
                ('valor_final', models.FloatField()),
                ('tolerancia', models.FloatField(default=1e-05)),
                ('max_iteraciones', models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SecanteResultado',
        ),
    ]
