# Generated by Django 5.2.1 on 2025-05-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secante_app', '0003_secante_delete_secanteresultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecantMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=255)),
                ('x0', models.FloatField()),
                ('x1', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('max_iteraciones', models.IntegerField(default=100)),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('iteraciones', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Secante',
        ),
    ]
