# Generated by Django 5.2.1 on 2025-05-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secante_app', '0004_secantmethod_delete_secante'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecanteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.TextField()),
                ('x0', models.FloatField()),
                ('x1', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('max_iteraciones', models.IntegerField()),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('iteraciones', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SecantMethod',
        ),
    ]
